-- V1: initial schema, matching the entities as of Milestone 6.5

CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name           VARCHAR(100) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    privacy_accepted_at TIMESTAMP(6) WITH TIME ZONE,
    created_at          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    transaction_date DATE NOT NULL,
    description      VARCHAR(255) NOT NULL,
    amount           NUMERIC(12, 2) NOT NULL,
    category         VARCHAR(30) NOT NULL,
    category_source  VARCHAR(10) NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_transactions_category CHECK (category IN (
        'INCOME','HOUSING','GROCERIES','TRANSPORT','AIRTIME_DATA','EATING_OUT',
        'ENTERTAINMENT','UTILITIES','HEALTH','EDUCATION','SHOPPING','TRANSFERS','FEES','OTHER')),
    CONSTRAINT ck_transactions_category_source CHECK (category_source IN ('RULE','AI','USER'))
);

CREATE TABLE budgets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    category      VARCHAR(30) NOT NULL,
    monthly_limit NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_budgets_user_category UNIQUE (user_id, category),
    CONSTRAINT ck_budgets_category CHECK (category IN (
        'INCOME','HOUSING','GROCERIES','TRANSPORT','AIRTIME_DATA','EATING_OUT',
        'ENTERTAINMENT','UTILITIES','HEALTH','EDUCATION','SHOPPING','TRANSFERS','FEES','OTHER'))
);

CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_reset_tokens_hash UNIQUE (token_hash)
);

-- PostgreSQL doesn't index foreign keys automatically; these speed up "my data" queries
CREATE INDEX idx_transactions_user_date ON transactions (user_id, transaction_date DESC);
CREATE INDEX idx_reset_tokens_user ON password_reset_tokens (user_id);